version: "3.9"

services:
#  document-converter-service:
#    image: document-converter-service:latest
#    container_name: document-converter-service
#    ports:
#      - "8080:8080"
#    networks:
#      - internal

  pdf-service:
    image: pdf-service:latest
    container_name: pdf-service
    environment:
      - CONVERTER_BASE_URL=http://document-converter-service:8080

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/appdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/appdb
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
    depends_on:
#      - document-converter-service
      - postgres
    ports:
      - "8081:8080"
    networks:
      - internal

  postgres:
    image: postgres:16
    container_name: postgres_test2
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres-data:
    driver: local
