server:
  port: 8080

spring:
  application:
    name: pdf-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sign_service
    username: postgres
    password: password
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

converter:
  base-url: http://document-converter-service:8080
  connect-timeout-ms: 5000
  read-timeout-ms: 60000

logging:
  level:
    root: INFO

